#pragma config(Sensor, in1,    pot1,           sensorPotentiometer)
#pragma config(Motor,  port1,           FrontRight,    tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           BackRight,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           BackLeft,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           Lift,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          FrontLeft,     tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
  // ..........................................................................
  // Insert user code here.
  // ..........................................................................

  // Remove this function call once you have "real" code.
  AutonomousCodePlaceholderForTesting();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
	int deadzone = 10;
	int position = 3000;
  while (true)
  {
  	if(vexRT[Ch3] > deadzone || vexRT[Ch3] < -deadzone || vexRT[Ch1] > deadzone || vexRT[Ch1] < -deadzone)
  	{
  		motor[FrontRight] = motor[BackRight] = -vexRT[Ch3] + vexRT[Ch1];
  		motor[FrontLeft] = motor[BackLeft] = -vexRT[Ch3] - vexRT[Ch1];
  	}
  	else
  	{
  		motor[FrontRight] = motor[FrontLeft] = motor[BackRight] = motor[BackLeft] = 0;
  	}

  	if (vexRT[Btn5U])
  	{
  		motor[Lift] = 90;
  	}
  	else if (vexRT[Btn5D])
  	{
  		motor[Lift] = -90;
  	}
  	else if (vexRT[Btn6U])
  	{
  		motor[Lift] = 45;
  	}
  	else if (vexRT[Btn6D])
  	{
  		motor[Lift] = -45;
  	}
  	else if (vexRT[Btn7U])
  	{
  		if (SensorValue[pot1] > (position-5))
  		{
  			motor[Lift] = -30;
  		}
  		else if (SensorValue[pot1] < (position+5))
  		{
  			motor[Lift] = 20;
  		}
  		else
  		{
  			motor[Lift] = 10;
  		}
  	}
  	else
  	{
  		motor[Lift] = 10;
  	}
  	wait1Msec(25);
  }

}
